<?php

namespace VB\ProductionBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * ProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProductionRepository extends \Doctrine\ORM\EntityRepository
{
	public function  myFindDQL()
    {

        $query = $this->_em->createQuery('SELECT r.dateReceipt,f.format,p.poids,p.idProduction,c.idCustomer FROM ProductionBundle:Production p, CustomerBundle:Customer c WHERE p.idProduction=c.idCustomer');
       $results=$query->getResult();


    return $results;
    }
}