<?php

namespace VB\ProductionBundle\Repository;

/**
 * ShipperAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ShipperAddressRepository extends \Doctrine\ORM\EntityRepository
{
}