<?php

namespace VB\OptionBundle\Repository;

/**
 * AdresseDomiciliataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AdresseDomiciliataireRepository extends \Doctrine\ORM\EntityRepository
{
}