<?php

namespace VB\OptionBundle\Repository;

/**
 * MailOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class MailOptionRepository extends \Doctrine\ORM\EntityRepository
{
}