<?php

namespace VB\OptionBundle\Repository;

/**
 * ScanOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ScanOptionRepository extends \Doctrine\ORM\EntityRepository
{
}