<?php

namespace VB\OptionBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * TypeEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TypeEntityRepository extends \Doctrine\ORM\EntityRepository
{

}