<?php

namespace VB\OptionBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * TypicalOfferRepositoryr
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TypicalOfferRepository extends \Doctrine\ORM\EntityRepository
{
    public function  myFindDQL()
    {

        $query = $this->_em->createQuery('SELECT o.priceOffer,e.typeEntity FROM VBOptionBundle:TypicalOffer o, VBOptionBundle:TypeEntity e, VBOptionBundle:FormEntity f WHERE o.idForm=f.idForm and f.idTypeEntity=e.idEntity');
       $results=$query->getResult();


    return $results;
    }

}