<?php

namespace VB\CustomerBundle\Repository;

/**
 * CustomerAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CustomerAdminRepository extends \Doctrine\ORM\EntityRepository
{
}