<?php

namespace VB\CustomerBundle\Repository;

/**
 * CustomerOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CustomerOptionRepository extends \Doctrine\ORM\EntityRepository
{
}