<?php

namespace VB\CustomerBundle\Repository;

/**
 * HistoricConnexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class HistoricConnexionRepository extends \Doctrine\ORM\EntityRepository
{
}